--PROCEDURES
select * from TB_FUNCIONARIO

CREATE OR ALTER PROCEDURE P_BUSCA --CRIA O PROCEDURE
	@COD_BUSCA INT -- PASSA UM PARAMETRO
	AS -- INICIA O PROCEDIMENTO
		SELECT * FROM TB_FUNCIONARIO 
				 WHERE CD_CARGO = @COD_BUSCA -- SELECIONA O FILTRO EM QUESTAO

EXEC P_BUSCA 3 --RODA O PROCEDURE PASSANDO O PARAMETRO QUE VAI SER USADO COMO FILTRO