-- TRIGGER
-- NOME DO TRIGGER
-- EM QUE TABELA (ON NOME_TABELA)
-- QUANDO X COISA ACONTECER (AFTER INSERT )
SELECT * FROM TB_CARGO
select * from TB_VENDAS

CREATE OR ALTER TRIGGER T_TRIGGER
	ON TB_CARGO	AFTER INSERT -- quando inserir algo na tabela "TB_CARGO"
	AS 
		BEGIN
			UPDATE TB_VENDAS -- ATUALIZAR TABELA BENDAS
			SET VALOR = VALOR + 50 --ADICIONANDO +50 NO CAMPO VALOR
			WHERE MATRICULA = 4 -- QUANDO A MATRICULA FOR 4
		END
	GO

INSERT INTO TB_CARGO (CD_CARGO,CARGO) VALUES (10,'SASA')-- ESSA RODA + TRIGGER
