CREATE TABLE TB_FUNCIONARIO (
MATRICULA INT NOT NULL PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(11) NOT NULL,
CARGO VARCHAR(50) NOT NULL,
FUNCAO VARCHAR(50) NULL,
SALARIO NUMERIC(10,2) NOT NULL,
COD_SETOR INT NOT NULL REFERENCES TB_SETOR (COD_SETOR)
)

CREATE TABLE TB_SETOR (
COD_SETOR INT NOT NULL PRIMARY KEY,
NM_SETOR VARCHAR(50) NOT NULL,
COD_DEPARTAMENTO INT NOT NULL REFERENCES
TB_DEPARTAMENTO(COD_DEPARTAMENTO)
)

CREATE TABLE TB_DEPARTAMENTO (
COD_DEPARTAMENTO INT NOT NULL PRIMARY KEY,
NM_DEPARTAMENTO VARCHAR(50) NOT NULL,
)

CREATE TABLE TB_AUX_FUNCIONARIO (
DATA_CARGA DATETIME NOT NULL,
MATRICULA INT NOT NULL,
NOME VARCHAR(60) NULL,
CPF VARCHAR(11) NULL,
CARGO VARCHAR(50) NULL,
FUNCAO VARCHAR(50) NULL,
SALARIO NUMERIC(10,2) NULL,
CODIGO_SETOR INT NULL,
SETOR VARCHAR(50) NULL,
CODIGO_DEPARTAMENTO INT NULL,
DEPARTAMENTO VARCHAR(50) NULL
)

CREATE TABLE DIM_FUNCIONARIO (
ID_FUNCIONARIO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
MATRICULA INT NOT NULL,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(11) NOT NULL,
CARGO VARCHAR(50) NOT NULL,
FUNCAO VARCHAR(50) NULL,
SALARIO NUMERIC(10,2) NOT NULL,
CODIGO_SETOR INT NULL,
SETOR VARCHAR(50) NOT NULL,
CODIGO_DEPARTAMENTO INT NULL,
DEPARTAMENTO VARCHAR(50) NOT NULL,
DT_INICIO DATETIME NOT NULL,
DT_FIM DATETIME NULL,
FL_CORRENTE VARCHAR(3) NOT NULL CHECK (FL_CORRENTE IN ('SIM','NAO'))
)

GO
CREATE PROCEDURE SP_OLTP_FUNCIONARIO (@DATA_CARGA DATETIME)
AS
	BEGIN
		DELETE FROM TB_AUX_FUNCIONARIO
		WHERE DATA_CARGA = @DATA_CARGA
		
		INSERT INTO TB_AUX_FUNCIONARIO 
		SELECT @DATA_CARGA, 
				F.MATRICULA,
				F.NOME,
				F.CPF,
				F.CARGO,
				F.FUNCAO,
				F.SALARIO,

				S.COD_SETOR,
				S.NM_SETOR,

				D.COD_DEPARTAMENTO,
				D.NM_DEPARTAMENTO

				FROM TB_FUNCIONARIO F
				JOIN TB_SETOR S
				ON S.COD_SETOR = F.COD_SETOR
				JOIN TB_DEPARTAMENTO D
				ON D.COD_DEPARTAMENTO = S.COD_DEPARTAMENTO
	END
GO